import _typeshed

Accessibility_NotReachable: int
Accessibility_Ok: int
Accessibility_Opened: int
Accessibility_OpenedExclusively: int
Accessibility_Unknown: int
BCL_BiColorBGRG: int
BCL_BiColorRGBG: int
BCL_Undefined: int
BufferHandlingMode_Pool: int
BufferHandlingMode_Stream: int
CameraEventAvailability_Mandatory: int
CameraEventAvailability_Optional: int
Cleanup_Delete: int
Cleanup_None: int
ComponentType_Calibration_STA: int
ComponentType_Confidence: int
ComponentType_Disparity: int
ComponentType_Error_STA: int
ComponentType_Intensity: int
ComponentType_IntensityCombined_STA: int
ComponentType_Range: int
ComponentType_RawCombined_STA: int
ComponentType_Reflectance: int
ComponentType_Scatter: int
ComponentType_Undefined: int
CompressionMode_BaslerFixRatio: int
CompressionMode_BaslerLossless: int
CompressionMode_Off: int
CompressionStatus_BufferOverflow: int
CompressionStatus_Error: int
CompressionStatus_Ok: int
Endianness_Auto: int
Endianness_Big: int
Endianness_Little: int
GigEActionCommandStatus_ActionLate: int
GigEActionCommandStatus_NoRefTime: int
GigEActionCommandStatus_Ok: int
GigEActionCommandStatus_Overflow: int
GrabLoop_ProvidedByInstantCamera: int
GrabLoop_ProvidedByUser: int
GrabStrategy_LatestImageOnly: int
GrabStrategy_LatestImages: int
GrabStrategy_OneByOne: int
GrabStrategy_UpcomingImage: int
ImageFileFormat_Bmp: int
ImageFileFormat_Dng: int
ImageFileFormat_Jpeg: int
ImageFileFormat_Png: int
ImageFileFormat_Raw: int
ImageFileFormat_Tiff: int
ImageOrientation_BottomUp: int
ImageOrientation_TopDown: int
InconvertibleEdgeHandling_Clip: int
InconvertibleEdgeHandling_Extend: int
InconvertibleEdgeHandling_SetZero: int
MonoConversionMethod_Gamma: int
MonoConversionMethod_Truncate: int
OutputBitAlignment_LsbAligned: int
OutputBitAlignment_MsbAligned: int
OutputOrientation_BottomUp: int
OutputOrientation_TopDown: int
OutputOrientation_Unchanged: int
PCF_BayerBG: int
PCF_BayerGB: int
PCF_BayerGR: int
PCF_BayerRG: int
PCF_Undefined: int
PIXEL_COLOR: int
PIXEL_CUSTOMTYPE: int
PIXEL_MONO: int
PYLON_VERSIONSTRING_BUILD: str
PYLON_VERSIONSTRING_EXTENSION: str
PYLON_VERSIONSTRING_GITHASH: str
PYLON_VERSIONSTRING_MAJOR: str
PYLON_VERSIONSTRING_MINOR: str
PYLON_VERSIONSTRING_SUBMINOR: str
PYLON_VERSION_BUILD: int
PYLON_VERSION_MAJOR: int
PYLON_VERSION_MINOR: int
PYLON_VERSION_SUBMINOR: int
PayloadType_ChunkData: int
PayloadType_DeviceSpecific: int
PayloadType_File: int
PayloadType_GenDC: int
PayloadType_Image: int
PayloadType_RawData: int
PayloadType_Undefined: int
PixelType_BGR10V1packed: int
PixelType_BGR10V2packed: int
PixelType_BGR10packed: int
PixelType_BGR12packed: int
PixelType_BGR8packed: int
PixelType_BGRA8packed: int
PixelType_BayerBG10: int
PixelType_BayerBG10p: int
PixelType_BayerBG12: int
PixelType_BayerBG12Packed: int
PixelType_BayerBG12p: int
PixelType_BayerBG16: int
PixelType_BayerBG8: int
PixelType_BayerGB10: int
PixelType_BayerGB10p: int
PixelType_BayerGB12: int
PixelType_BayerGB12Packed: int
PixelType_BayerGB12p: int
PixelType_BayerGB16: int
PixelType_BayerGB8: int
PixelType_BayerGR10: int
PixelType_BayerGR10p: int
PixelType_BayerGR12: int
PixelType_BayerGR12Packed: int
PixelType_BayerGR12p: int
PixelType_BayerGR16: int
PixelType_BayerGR8: int
PixelType_BayerRG10: int
PixelType_BayerRG10p: int
PixelType_BayerRG12: int
PixelType_BayerRG12Packed: int
PixelType_BayerRG12p: int
PixelType_BayerRG16: int
PixelType_BayerRG8: int
PixelType_BiColorBGRG10: int
PixelType_BiColorBGRG10p: int
PixelType_BiColorBGRG12: int
PixelType_BiColorBGRG12p: int
PixelType_BiColorBGRG8: int
PixelType_BiColorRGBG10: int
PixelType_BiColorRGBG10p: int
PixelType_BiColorRGBG12: int
PixelType_BiColorRGBG12p: int
PixelType_BiColorRGBG8: int
PixelType_Confidence16: int
PixelType_Confidence8: int
PixelType_Coord3D_ABC32f: int
PixelType_Coord3D_C16: int
PixelType_Coord3D_C8: int
PixelType_Data16: int
PixelType_Data16s: int
PixelType_Data32: int
PixelType_Data32f: int
PixelType_Data32s: int
PixelType_Data64: int
PixelType_Data64f: int
PixelType_Data64s: int
PixelType_Data8: int
PixelType_Data8s: int
PixelType_Double: int
PixelType_Error8: int
PixelType_Mono10: int
PixelType_Mono10p: int
PixelType_Mono10packed: int
PixelType_Mono12: int
PixelType_Mono12p: int
PixelType_Mono12packed: int
PixelType_Mono16: int
PixelType_Mono1packed: int
PixelType_Mono2packed: int
PixelType_Mono4packed: int
PixelType_Mono8: int
PixelType_Mono8signed: int
PixelType_RGB10packed: int
PixelType_RGB10planar: int
PixelType_RGB12V1packed: int
PixelType_RGB12packed: int
PixelType_RGB12planar: int
PixelType_RGB16packed: int
PixelType_RGB16planar: int
PixelType_RGB8packed: int
PixelType_RGB8planar: int
PixelType_RGBA8packed: int
PixelType_Undefined: int
PixelType_YCbCr420_8_YY_CbCr_Semiplanar: int
PixelType_YCbCr422_8_YY_CbCr_Semiplanar: int
PixelType_YUV411packed: int
PixelType_YUV420planar: int
PixelType_YUV422_YUYV_Packed: int
PixelType_YUV422packed: int
PixelType_YUV422planar: int
PixelType_YUV444packed: int
PixelType_YUV444planar: int
PylonImageWindow_showDefault: int
PylonImageWindow_useDefault: int
RegistrationMode_Append: int
RegistrationMode_ReplaceAll: int
TimeoutHandling_Return: int
TimeoutHandling_ThrowException: int
cvar: _typeshed.Incomplete
waitex_abandoned: int
waitex_alerted: int
waitex_signaled: int
waitex_timeout: int

def AcquireContinuousConfiguration_ApplyConfiguration(*args, **kwargs): ...
def AcquireContinuousConfiguration_OnOpened(*args, **kwargs): ...
def AcquireContinuousConfiguration_swiginit(*args, **kwargs): ...
def AcquireContinuousConfiguration_swigregister(*args, **kwargs): ...
def AcquireSingleFrameConfiguration_ApplyConfiguration(*args, **kwargs): ...
def AcquireSingleFrameConfiguration_OnOpened(*args, **kwargs): ...
def AcquireSingleFrameConfiguration_swiginit(*args, **kwargs): ...
def AcquireSingleFrameConfiguration_swigregister(*args, **kwargs): ...
def ActionTriggerConfiguration_ApplyConfiguration(*args, **kwargs): ...
def ActionTriggerConfiguration_swiginit(*args, **kwargs): ...
def ActionTriggerConfiguration_swigregister(*args, **kwargs): ...
def BitDepth(*args, **kwargs): ...
def BitPerPixel(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_AdditionalLeftShift_get(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_AdditionalLeftShift_set(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_Gamma_get(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_Gamma_set(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_InconvertibleEdgeHandling_get(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_InconvertibleEdgeHandling_set(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_MaxNumThreads_get(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_MaxNumThreads_set(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_MonoConversionMethod_get(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_MonoConversionMethod_set(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_OutputBitAlignment_get(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_OutputBitAlignment_set(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_OutputOrientation_get(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_OutputOrientation_set(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_OutputPaddingX_get(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_OutputPaddingX_set(*args, **kwargs): ...
def CImageFormatConverterParams_Params_v10_0_0_swigregister(*args, **kwargs): ...
def CInfoBase_GetDeviceClass(*args, **kwargs): ...
def CInfoBase_GetFriendlyName(*args, **kwargs): ...
def CInfoBase_GetFullName(*args, **kwargs): ...
def CInfoBase_GetPropertyAvailable(*args, **kwargs): ...
def CInfoBase_GetPropertyNames(*args, **kwargs): ...
def CInfoBase_GetPropertyNotAvailable(*args, **kwargs): ...
def CInfoBase_GetPropertyValue(*args, **kwargs): ...
def CInfoBase_GetTLType(*args, **kwargs): ...
def CInfoBase_GetVendorName(*args, **kwargs): ...
def CInfoBase_IsDeviceClassAvailable(*args, **kwargs): ...
def CInfoBase_IsFriendlyNameAvailable(*args, **kwargs): ...
def CInfoBase_IsFullNameAvailable(*args, **kwargs): ...
def CInfoBase_IsSubset(*args, **kwargs): ...
def CInfoBase_IsTLTypeAvailable(*args, **kwargs): ...
def CInfoBase_IsUserProvided(*args, **kwargs): ...
def CInfoBase_IsVendorNameAvailable(*args, **kwargs): ...
def CInfoBase_SetDeviceClass(*args, **kwargs): ...
def CInfoBase_SetFriendlyName(*args, **kwargs): ...
def CInfoBase_SetFullName(*args, **kwargs): ...
def CInfoBase_SetPropertyValue(*args, **kwargs): ...
def CInfoBase_SetTLType(*args, **kwargs): ...
def CInfoBase_SetVendorName(*args, **kwargs): ...
def CInfoBase___eq__(*args, **kwargs): ...
def CInfoBase___lt__(*args, **kwargs): ...
def CInfoBase_swigregister(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_AcquisitionStartStopExecutionEnable_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_AcquisitionStartStopExecutionEnable_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_BufferHandlingMode_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_BufferHandlingMode_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_ChunkNodeMapsEnable_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_ChunkNodeMapsEnable_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_ClearBufferModeEnable_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_ClearBufferModeEnable_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabCameraEvents_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabCameraEvents_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabLoopThreadPriorityOverride_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabLoopThreadPriorityOverride_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabLoopThreadPriority_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabLoopThreadPriority_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabLoopThreadTimeout_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabLoopThreadTimeout_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabLoopThreadUseTimeout_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_GrabLoopThreadUseTimeout_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_InternalGrabEngineThreadPriorityOverride_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_InternalGrabEngineThreadPriorityOverride_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_InternalGrabEngineThreadPriority_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_InternalGrabEngineThreadPriority_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MaxNumBuffer_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MaxNumBuffer_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MaxNumGrabResults_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MaxNumGrabResults_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MaxNumQueuedBuffer_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MaxNumQueuedBuffer_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MigrationModeActive_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MigrationModeActive_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MonitorModeActive_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_MonitorModeActive_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_NumEmptyBuffers_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_NumEmptyBuffers_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_NumQueuedBuffers_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_NumQueuedBuffers_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_NumReadyBuffers_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_NumReadyBuffers_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_OutputQueueSize_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_OutputQueueSize_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_StaticChunkNodeMapPoolSize_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_StaticChunkNodeMapPoolSize_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_UseExtendedIdIfAvailable_get(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_UseExtendedIdIfAvailable_set(*args, **kwargs): ...
def CInstantCameraParams_Params_v10_0_0_swigregister(*args, **kwargs): ...
def CameraEventHandler_DestroyCameraEventHandler(*args, **kwargs): ...
def CameraEventHandler_OnCameraEvent(*args, **kwargs): ...
def CameraEventHandler_OnCameraEventHandlerDeregistered(*args, **kwargs): ...
def CameraEventHandler_OnCameraEventHandlerRegistered(*args, **kwargs): ...
def CameraEventHandler_swiginit(*args, **kwargs): ...
def CameraEventHandler_swigregister(*args, **kwargs): ...
def CompressionInfo_compressionStatus_get(*args, **kwargs): ...
def CompressionInfo_compressionStatus_set(*args, **kwargs): ...
def CompressionInfo_decompressedImageSize_get(*args, **kwargs): ...
def CompressionInfo_decompressedImageSize_set(*args, **kwargs): ...
def CompressionInfo_decompressedPayloadSize_get(*args, **kwargs): ...
def CompressionInfo_decompressedPayloadSize_set(*args, **kwargs): ...
def CompressionInfo_hasCompressedImage_get(*args, **kwargs): ...
def CompressionInfo_hasCompressedImage_set(*args, **kwargs): ...
def CompressionInfo_height_get(*args, **kwargs): ...
def CompressionInfo_height_set(*args, **kwargs): ...
def CompressionInfo_lossy_get(*args, **kwargs): ...
def CompressionInfo_lossy_set(*args, **kwargs): ...
def CompressionInfo_offsetX_get(*args, **kwargs): ...
def CompressionInfo_offsetX_set(*args, **kwargs): ...
def CompressionInfo_offsetY_get(*args, **kwargs): ...
def CompressionInfo_offsetY_set(*args, **kwargs): ...
def CompressionInfo_paddingX_get(*args, **kwargs): ...
def CompressionInfo_paddingX_set(*args, **kwargs): ...
def CompressionInfo_paddingY_get(*args, **kwargs): ...
def CompressionInfo_paddingY_set(*args, **kwargs): ...
def CompressionInfo_pixelType_get(*args, **kwargs): ...
def CompressionInfo_pixelType_set(*args, **kwargs): ...
def CompressionInfo_swiginit(*args, **kwargs): ...
def CompressionInfo_swigregister(*args, **kwargs): ...
def CompressionInfo_width_get(*args, **kwargs): ...
def CompressionInfo_width_set(*args, **kwargs): ...
def ComputeBufferSize(*args, **kwargs): ...
def ComputePaddingX(*args, **kwargs): ...
def ComputeStride(*args, **kwargs): ...
def ConfigurationEventHandler_DestroyConfiguration(*args, **kwargs): ...
def ConfigurationEventHandler_OnAttach(*args, **kwargs): ...
def ConfigurationEventHandler_OnAttached(*args, **kwargs): ...
def ConfigurationEventHandler_OnCameraDeviceRemoved(*args, **kwargs): ...
def ConfigurationEventHandler_OnClose(*args, **kwargs): ...
def ConfigurationEventHandler_OnClosed(*args, **kwargs): ...
def ConfigurationEventHandler_OnConfigurationDeregistered(*args, **kwargs): ...
def ConfigurationEventHandler_OnConfigurationRegistered(*args, **kwargs): ...
def ConfigurationEventHandler_OnDestroy(*args, **kwargs): ...
def ConfigurationEventHandler_OnDestroyed(*args, **kwargs): ...
def ConfigurationEventHandler_OnDetach(*args, **kwargs): ...
def ConfigurationEventHandler_OnDetached(*args, **kwargs): ...
def ConfigurationEventHandler_OnGrabError(*args, **kwargs): ...
def ConfigurationEventHandler_OnGrabStart(*args, **kwargs): ...
def ConfigurationEventHandler_OnGrabStarted(*args, **kwargs): ...
def ConfigurationEventHandler_OnGrabStop(*args, **kwargs): ...
def ConfigurationEventHandler_OnGrabStopped(*args, **kwargs): ...
def ConfigurationEventHandler_OnOpen(*args, **kwargs): ...
def ConfigurationEventHandler_OnOpened(*args, **kwargs): ...
def ConfigurationEventHandler_swiginit(*args, **kwargs): ...
def ConfigurationEventHandler_swigregister(*args, **kwargs): ...
def DeviceInfo_GetAddress(*args, **kwargs): ...
def DeviceInfo_GetDefaultGateway(*args, **kwargs): ...
def DeviceInfo_GetDeviceFactory(*args, **kwargs): ...
def DeviceInfo_GetDeviceGUID(*args, **kwargs): ...
def DeviceInfo_GetDeviceID(*args, **kwargs): ...
def DeviceInfo_GetDeviceIdx(*args, **kwargs): ...
def DeviceInfo_GetDeviceSpecificString(*args, **kwargs): ...
def DeviceInfo_GetDeviceVersion(*args, **kwargs): ...
def DeviceInfo_GetDeviceXMLFileOverride(*args, **kwargs): ...
def DeviceInfo_GetDriverKeyName(*args, **kwargs): ...
def DeviceInfo_GetInitialBaudRate(*args, **kwargs): ...
def DeviceInfo_GetInterface(*args, **kwargs): ...
def DeviceInfo_GetInterfaceID(*args, **kwargs): ...
def DeviceInfo_GetIpAddress(*args, **kwargs): ...
def DeviceInfo_GetIpConfigCurrent(*args, **kwargs): ...
def DeviceInfo_GetIpConfigOptions(*args, **kwargs): ...
def DeviceInfo_GetMacAddress(*args, **kwargs): ...
def DeviceInfo_GetManufacturerInfo(*args, **kwargs): ...
def DeviceInfo_GetModelName(*args, **kwargs): ...
def DeviceInfo_GetPortID(*args, **kwargs): ...
def DeviceInfo_GetPortNr(*args, **kwargs): ...
def DeviceInfo_GetPortSpecificString(*args, **kwargs): ...
def DeviceInfo_GetProductId(*args, **kwargs): ...
def DeviceInfo_GetSerialNumber(*args, **kwargs): ...
def DeviceInfo_GetSubnetAddress(*args, **kwargs): ...
def DeviceInfo_GetSubnetMask(*args, **kwargs): ...
def DeviceInfo_GetTransferMode(*args, **kwargs): ...
def DeviceInfo_GetUsbDriverType(*args, **kwargs): ...
def DeviceInfo_GetUserDefinedName(*args, **kwargs): ...
def DeviceInfo_GetVendorId(*args, **kwargs): ...
def DeviceInfo_GetXMLSource(*args, **kwargs): ...
def DeviceInfo_IsAddressAvailable(*args, **kwargs): ...
def DeviceInfo_IsAutoIpActive(*args, **kwargs): ...
def DeviceInfo_IsAutoIpSupported(*args, **kwargs): ...
def DeviceInfo_IsDefaultGatewayAvailable(*args, **kwargs): ...
def DeviceInfo_IsDeviceFactoryAvailable(*args, **kwargs): ...
def DeviceInfo_IsDeviceGUIDAvailable(*args, **kwargs): ...
def DeviceInfo_IsDeviceIDAvailable(*args, **kwargs): ...
def DeviceInfo_IsDeviceIdxAvailable(*args, **kwargs): ...
def DeviceInfo_IsDeviceSpecificStringAvailable(*args, **kwargs): ...
def DeviceInfo_IsDeviceVersionAvailable(*args, **kwargs): ...
def DeviceInfo_IsDeviceXMLFileOverrideAvailable(*args, **kwargs): ...
def DeviceInfo_IsDhcpActive(*args, **kwargs): ...
def DeviceInfo_IsDhcpSupported(*args, **kwargs): ...
def DeviceInfo_IsDriverKeyNameAvailable(*args, **kwargs): ...
def DeviceInfo_IsInitialBaudRateAvailable(*args, **kwargs): ...
def DeviceInfo_IsInterfaceAvailable(*args, **kwargs): ...
def DeviceInfo_IsInterfaceIDAvailable(*args, **kwargs): ...
def DeviceInfo_IsIpAddressAvailable(*args, **kwargs): ...
def DeviceInfo_IsIpConfigCurrentAvailable(*args, **kwargs): ...
def DeviceInfo_IsIpConfigOptionsAvailable(*args, **kwargs): ...
def DeviceInfo_IsMacAddressAvailable(*args, **kwargs): ...
def DeviceInfo_IsManufacturerInfoAvailable(*args, **kwargs): ...
def DeviceInfo_IsModelNameAvailable(*args, **kwargs): ...
def DeviceInfo_IsPersistentIpActive(*args, **kwargs): ...
def DeviceInfo_IsPersistentIpSupported(*args, **kwargs): ...
def DeviceInfo_IsPortIDAvailable(*args, **kwargs): ...
def DeviceInfo_IsPortNrAvailable(*args, **kwargs): ...
def DeviceInfo_IsPortSpecificStringAvailable(*args, **kwargs): ...
def DeviceInfo_IsProductIdAvailable(*args, **kwargs): ...
def DeviceInfo_IsSerialNumberAvailable(*args, **kwargs): ...
def DeviceInfo_IsSubnetAddressAvailable(*args, **kwargs): ...
def DeviceInfo_IsSubnetMaskAvailable(*args, **kwargs): ...
def DeviceInfo_IsSubset(*args, **kwargs): ...
def DeviceInfo_IsTransferModeAvailable(*args, **kwargs): ...
def DeviceInfo_IsUsbDriverTypeAvailable(*args, **kwargs): ...
def DeviceInfo_IsUserDefinedNameAvailable(*args, **kwargs): ...
def DeviceInfo_IsVendorIdAvailable(*args, **kwargs): ...
def DeviceInfo_IsXMLSourceAvailable(*args, **kwargs): ...
def DeviceInfo_SetAddress(*args, **kwargs): ...
def DeviceInfo_SetDefaultGateway(*args, **kwargs): ...
def DeviceInfo_SetDeviceClass(*args, **kwargs): ...
def DeviceInfo_SetDeviceFactory(*args, **kwargs): ...
def DeviceInfo_SetDeviceID(*args, **kwargs): ...
def DeviceInfo_SetDeviceSpecificString(*args, **kwargs): ...
def DeviceInfo_SetDeviceVersion(*args, **kwargs): ...
def DeviceInfo_SetDeviceXMLFileOverride(*args, **kwargs): ...
def DeviceInfo_SetFriendlyName(*args, **kwargs): ...
def DeviceInfo_SetFullName(*args, **kwargs): ...
def DeviceInfo_SetInitialBaudRate(*args, **kwargs): ...
def DeviceInfo_SetInterface(*args, **kwargs): ...
def DeviceInfo_SetInterfaceID(*args, **kwargs): ...
def DeviceInfo_SetIpAddress(*args, **kwargs): ...
def DeviceInfo_SetIpConfigCurrent(*args, **kwargs): ...
def DeviceInfo_SetIpConfigOptions(*args, **kwargs): ...
def DeviceInfo_SetMacAddress(*args, **kwargs): ...
def DeviceInfo_SetModelName(*args, **kwargs): ...
def DeviceInfo_SetPortID(*args, **kwargs): ...
def DeviceInfo_SetPortNr(*args, **kwargs): ...
def DeviceInfo_SetPortSpecificString(*args, **kwargs): ...
def DeviceInfo_SetPropertyValue(*args, **kwargs): ...
def DeviceInfo_SetSerialNumber(*args, **kwargs): ...
def DeviceInfo_SetSubnetAddress(*args, **kwargs): ...
def DeviceInfo_SetSubnetMask(*args, **kwargs): ...
def DeviceInfo_SetUserDefinedName(*args, **kwargs): ...
def DeviceInfo_SetVendorName(*args, **kwargs): ...
def DeviceInfo_SetXMLSource(*args, **kwargs): ...
def DeviceInfo___lt__(*args, **kwargs): ...
def DeviceInfo_swiginit(*args, **kwargs): ...
def DeviceInfo_swigregister(*args, **kwargs): ...
def DisplayImage(*args, **kwargs): ...
def FeaturePersistence_Load(*args, **kwargs): ...
def FeaturePersistence_LoadFromString(*args, **kwargs): ...
def FeaturePersistence_Save(*args, **kwargs): ...
def FeaturePersistence_SaveToString(*args, **kwargs): ...
def FeaturePersistence_swigregister(*args, **kwargs): ...
def GetBiColorLocation(*args, **kwargs): ...
def GetPixelColorFilter(*args, **kwargs): ...
def GetPixelIncrementX(*args, **kwargs): ...
def GetPixelIncrementY(*args, **kwargs): ...
def GetPixelTypesForUnpacking(*args, **kwargs): ...
def GetPlanePixelType(*args, **kwargs): ...
def GetPylonVersion(*args, **kwargs): ...
def GetPylonVersionString(*args, **kwargs): ...
def GigETransportLayer_AnnounceRemoteDevice(*args, **kwargs): ...
def GigETransportLayer_BroadcastIpConfiguration(*args, **kwargs): ...
def GigETransportLayer_EnumerateAllDevices(*args, **kwargs): ...
def GigETransportLayer_ForceIp(*args, **kwargs): ...
def GigETransportLayer_IssueActionCommandNoWait(*args, **kwargs): ...
def GigETransportLayer_IssueActionCommandWait(*args, **kwargs): ...
def GigETransportLayer_IssueScheduledActionCommandNoWait(*args, **kwargs): ...
def GigETransportLayer_IssueScheduledActionCommandWait(*args, **kwargs): ...
def GigETransportLayer_RenounceRemoteDevice(*args, **kwargs): ...
def GigETransportLayer_RestartIpConfiguration(*args, **kwargs): ...
def GigETransportLayer_swigregister(*args, **kwargs): ...
def GrabResultData_CheckCRC(*args, **kwargs): ...
def GrabResultData_GetBlockID(*args, **kwargs): ...
def GrabResultData_GetBuffer(*args, **kwargs): ...
def GrabResultData_GetBufferContext(*args, **kwargs): ...
def GrabResultData_GetBufferSize(*args, **kwargs): ...
def GrabResultData_GetCameraContext(*args, **kwargs): ...
def GrabResultData_GetChunkDataNodeMap(*args, **kwargs): ...
def GrabResultData_GetDataComponent(*args, **kwargs): ...
def GrabResultData_GetDataComponentCount(*args, **kwargs): ...
def GrabResultData_GetDataContainer(*args, **kwargs): ...
def GrabResultData_GetErrorCode(*args, **kwargs): ...
def GrabResultData_GetErrorDescription(*args, **kwargs): ...
def GrabResultData_GetGrabResultDataImpl(*args, **kwargs): ...
def GrabResultData_GetHeight(*args, **kwargs): ...
def GrabResultData_GetID(*args, **kwargs): ...
def GrabResultData_GetImageBuffer(*args, **kwargs): ...
def GrabResultData_GetImageMemoryView(*args, **kwargs): ...
def GrabResultData_GetImageNumber(*args, **kwargs): ...
def GrabResultData_GetImageSize(*args, **kwargs): ...
def GrabResultData_GetMemoryView(*args, **kwargs): ...
def GrabResultData_GetNumberOfSkippedImages(*args, **kwargs): ...
def GrabResultData_GetOffsetX(*args, **kwargs): ...
def GrabResultData_GetOffsetY(*args, **kwargs): ...
def GrabResultData_GetPaddingX(*args, **kwargs): ...
def GrabResultData_GetPaddingY(*args, **kwargs): ...
def GrabResultData_GetPayloadSize(*args, **kwargs): ...
def GrabResultData_GetPayloadType(*args, **kwargs): ...
def GrabResultData_GetPixelType(*args, **kwargs): ...
def GrabResultData_GetStride(*args, **kwargs): ...
def GrabResultData_GetTimeStamp(*args, **kwargs): ...
def GrabResultData_GetWidth(*args, **kwargs): ...
def GrabResultData_GrabSucceeded(*args, **kwargs): ...
def GrabResultData_HasCRC(*args, **kwargs): ...
def GrabResultData_IsChunkDataAvailable(*args, **kwargs): ...
def GrabResultData__Unpack10or12BitPacked(*args, **kwargs): ...
def GrabResultData_swigregister(*args, **kwargs): ...
def GrabResult_CheckCRC(*args, **kwargs): ...
def GrabResult_GetBlockID(*args, **kwargs): ...
def GrabResult_GetBuffer(*args, **kwargs): ...
def GrabResult_GetBufferContext(*args, **kwargs): ...
def GrabResult_GetBufferSize(*args, **kwargs): ...
def GrabResult_GetCameraContext(*args, **kwargs): ...
def GrabResult_GetChunkDataNodeMap(*args, **kwargs): ...
def GrabResult_GetDataComponent(*args, **kwargs): ...
def GrabResult_GetDataComponentCount(*args, **kwargs): ...
def GrabResult_GetDataContainer(*args, **kwargs): ...
def GrabResult_GetErrorCode(*args, **kwargs): ...
def GrabResult_GetErrorDescription(*args, **kwargs): ...
def GrabResult_GetGrabResultDataImpl(*args, **kwargs): ...
def GrabResult_GetHeight(*args, **kwargs): ...
def GrabResult_GetID(*args, **kwargs): ...
def GrabResult_GetImageBuffer(*args, **kwargs): ...
def GrabResult_GetImageMemoryView(*args, **kwargs): ...
def GrabResult_GetImageNumber(*args, **kwargs): ...
def GrabResult_GetImageSize(*args, **kwargs): ...
def GrabResult_GetMemoryView(*args, **kwargs): ...
def GrabResult_GetNumberOfSkippedImages(*args, **kwargs): ...
def GrabResult_GetOffsetX(*args, **kwargs): ...
def GrabResult_GetOffsetY(*args, **kwargs): ...
def GrabResult_GetPaddingX(*args, **kwargs): ...
def GrabResult_GetPaddingY(*args, **kwargs): ...
def GrabResult_GetPayloadSize(*args, **kwargs): ...
def GrabResult_GetPayloadType(*args, **kwargs): ...
def GrabResult_GetPixelType(*args, **kwargs): ...
def GrabResult_GetStride(*args, **kwargs): ...
def GrabResult_GetTimeStamp(*args, **kwargs): ...
def GrabResult_GetWidth(*args, **kwargs): ...
def GrabResult_GrabSucceeded(*args, **kwargs): ...
def GrabResult_HasCRC(*args, **kwargs): ...
def GrabResult_IsChunkDataAvailable(*args, **kwargs): ...
def GrabResult_IsUnique(*args, **kwargs): ...
def GrabResult_IsValid(*args, **kwargs): ...
def GrabResult_Release(*args, **kwargs): ...
def GrabResult__Unpack10or12BitPacked(*args, **kwargs): ...
def GrabResult___deref__(*args, **kwargs): ...
def GrabResult___nonzero__(*args, **kwargs): ...
def GrabResult_swiginit(*args, **kwargs): ...
def GrabResult_swigregister(*args, **kwargs): ...
def HasAlpha(*args, **kwargs): ...
def IDeviceFactory_CreateDevice(*args, **kwargs): ...
def IDeviceFactory_CreateFirstDevice(*args, **kwargs): ...
def IDeviceFactory_DestroyDevice(*args, **kwargs): ...
def IDeviceFactory_EnumerateDevices(*args, **kwargs): ...
def IDeviceFactory_IsDeviceAccessible(*args, **kwargs): ...
def IDeviceFactory_swigregister(*args, **kwargs): ...
def IProperties_GetPropertyAvailable(*args, **kwargs): ...
def IProperties_GetPropertyNames(*args, **kwargs): ...
def IProperties_GetPropertyValue(*args, **kwargs): ...
def IProperties_IsSubset(*args, **kwargs): ...
def IProperties_SetPropertyValue(*args, **kwargs): ...
def IProperties_swigregister(*args, **kwargs): ...
def IReusableImage_IsAdditionalPaddingSupported(*args, **kwargs): ...
def IReusableImage_IsSupportedPixelType(*args, **kwargs): ...
def IReusableImage_Release(*args, **kwargs): ...
def IReusableImage_Reset(*args, **kwargs): ...
def IReusableImage_swigregister(*args, **kwargs): ...
def ImageDecompressor_ComputeCompressionDescriptorHash(*args, **kwargs): ...
def ImageDecompressor_DecompressImage(*args, **kwargs): ...
def ImageDecompressor_GetCompressionDescriptorHash(*args, **kwargs): ...
def ImageDecompressor_GetCompressionInfo(*args, **kwargs): ...
def ImageDecompressor_GetCurrentCompressionDescriptorHash(*args, **kwargs): ...
def ImageDecompressor_HasCompressionDescriptor(*args, **kwargs): ...
def ImageDecompressor_ResetCompressionDescriptor(*args, **kwargs): ...
def ImageDecompressor_SetCompressionDescriptor(*args, **kwargs): ...
def ImageDecompressor___eq__(*args, **kwargs): ...
def ImageDecompressor_swiginit(*args, **kwargs): ...
def ImageDecompressor_swigregister(*args, **kwargs): ...
def ImageEventHandler_DestroyImageEventHandler(*args, **kwargs): ...
def ImageEventHandler_OnImageEventHandlerDeregistered(*args, **kwargs): ...
def ImageEventHandler_OnImageEventHandlerRegistered(*args, **kwargs): ...
def ImageEventHandler_OnImageGrabbed(*args, **kwargs): ...
def ImageEventHandler_OnImagesSkipped(*args, **kwargs): ...
def ImageEventHandler_swiginit(*args, **kwargs): ...
def ImageEventHandler_swigregister(*args, **kwargs): ...
def ImageFormatConverterParams_Params__GetBaseType_AdditionalLeftShift(*args, **kwargs): ...
def ImageFormatConverterParams_Params__GetBaseType_Gamma(*args, **kwargs): ...
def ImageFormatConverterParams_Params__GetBaseType_OutputPaddingX(*args, **kwargs): ...
def ImageFormatConverterParams_Params__GetEnum_InconvertibleEdgeHandling(*args, **kwargs): ...
def ImageFormatConverterParams_Params__GetEnum_MonoConversionMethod(*args, **kwargs): ...
def ImageFormatConverterParams_Params__GetEnum_OutputBitAlignment(*args, **kwargs): ...
def ImageFormatConverterParams_Params__GetEnum_OutputOrientation(*args, **kwargs): ...
def ImageFormatConverterParams_Params_swigregister(*args, **kwargs): ...
def ImageFormatConverter_Convert(*args, **kwargs): ...
def ImageFormatConverter_GetBufferSizeForConversion(*args, **kwargs): ...
def ImageFormatConverter_GetNodeMap(*args, **kwargs): ...
def ImageFormatConverter_GetOutputPixelFormat(*args, **kwargs): ...
def ImageFormatConverter_ImageHasDestinationFormat(*args, **kwargs): ...
def ImageFormatConverter_Initialize(*args, **kwargs): ...
def ImageFormatConverter_IsInitialized(*args, **kwargs): ...
def ImageFormatConverter_IsSupportedInputFormat(*args, **kwargs): ...
def ImageFormatConverter_IsSupportedOutputFormat(*args, **kwargs): ...
def ImageFormatConverter_SetOutputPixelFormat(*args, **kwargs): ...
def ImageFormatConverter_Uninitialize(*args, **kwargs): ...
def ImageFormatConverter_swiginit(*args, **kwargs): ...
def ImageFormatConverter_swigregister(*args, **kwargs): ...
def ImagePersistenceOptions_GetQuality(*args, **kwargs): ...
def ImagePersistenceOptions_SetQuality(*args, **kwargs): ...
def ImagePersistenceOptions_swiginit(*args, **kwargs): ...
def ImagePersistenceOptions_swigregister(*args, **kwargs): ...
def Image_GetBuffer(*args, **kwargs): ...
def Image_GetHeight(*args, **kwargs): ...
def Image_GetImageSize(*args, **kwargs): ...
def Image_GetOrientation(*args, **kwargs): ...
def Image_GetPaddingX(*args, **kwargs): ...
def Image_GetPixelType(*args, **kwargs): ...
def Image_GetStride(*args, **kwargs): ...
def Image_GetWidth(*args, **kwargs): ...
def Image_IsUnique(*args, **kwargs): ...
def Image_IsValid(*args, **kwargs): ...
def Image_swigregister(*args, **kwargs): ...
def InstantCameraArray_Close(*args, **kwargs): ...
def InstantCameraArray_DestroyDevice(*args, **kwargs): ...
def InstantCameraArray_DetachDevice(*args, **kwargs): ...
def InstantCameraArray_GetSize(*args, **kwargs): ...
def InstantCameraArray_Initialize(*args, **kwargs): ...
def InstantCameraArray_IsCameraDeviceRemoved(*args, **kwargs): ...
def InstantCameraArray_IsGrabbing(*args, **kwargs): ...
def InstantCameraArray_IsOpen(*args, **kwargs): ...
def InstantCameraArray_IsPylonDeviceAttached(*args, **kwargs): ...
def InstantCameraArray_Open(*args, **kwargs): ...
def InstantCameraArray_RetrieveResult(*args, **kwargs): ...
def InstantCameraArray_StartGrabbing(*args, **kwargs): ...
def InstantCameraArray_StopGrabbing(*args, **kwargs): ...
def InstantCameraArray___getitem__(*args, **kwargs): ...
def InstantCameraArray_swiginit(*args, **kwargs): ...
def InstantCameraArray_swigregister(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_ChunkNodeMapsEnable(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_GrabCameraEvents(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_GrabLoopThreadPriority(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_GrabLoopThreadPriorityOverride(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_GrabLoopThreadTimeout(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_GrabLoopThreadUseTimeout(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_InternalGrabEngineThreadPriority(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_InternalGrabEngineThreadPriorityOverride(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_MaxNumBuffer(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_MaxNumGrabResults(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_MaxNumQueuedBuffer(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_MonitorModeActive(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_NumEmptyBuffers(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_NumQueuedBuffers(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_NumReadyBuffers(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_OutputQueueSize(*args, **kwargs): ...
def InstantCameraParams_Params__GetBaseType_StaticChunkNodeMapPoolSize(*args, **kwargs): ...
def InstantCameraParams_Params_swigregister(*args, **kwargs): ...
def InstantCamera_Attach(*args, **kwargs): ...
def InstantCamera_Close(*args, **kwargs): ...
def InstantCamera_DeregisterCameraEventHandler(*args, **kwargs): ...
def InstantCamera_DeregisterConfiguration(*args, **kwargs): ...
def InstantCamera_DeregisterImageEventHandler(*args, **kwargs): ...
def InstantCamera_DestroyDevice(*args, **kwargs): ...
def InstantCamera_DetachDevice(*args, **kwargs): ...
def InstantCamera_ExecuteSoftwareTrigger(*args, **kwargs): ...
def InstantCamera_GetCameraContext(*args, **kwargs): ...
def InstantCamera_GetCameraEventWaitObject(*args, **kwargs): ...
def InstantCamera_GetDeviceInfo(*args, **kwargs): ...
def InstantCamera_GetEventGrabberNodeMap(*args, **kwargs): ...
def InstantCamera_GetGrabResultWaitObject(*args, **kwargs): ...
def InstantCamera_GetGrabStopWaitObject(*args, **kwargs): ...
def InstantCamera_GetInstantCameraNodeMap(*args, **kwargs): ...
def InstantCamera_GetNodeMap(*args, **kwargs): ...
def InstantCamera_GetQueuedBufferCount(*args, **kwargs): ...
def InstantCamera_GetSfncVersion(*args, **kwargs): ...
def InstantCamera_GetStreamGrabberNodeMap(*args, **kwargs): ...
def InstantCamera_GetTLNodeMap(*args, **kwargs): ...
def InstantCamera_GrabOne(*args, **kwargs): ...
def InstantCamera_HasOwnership(*args, **kwargs): ...
def InstantCamera_IsCameraDeviceRemoved(*args, **kwargs): ...
def InstantCamera_IsCameraLink(*args, **kwargs): ...
def InstantCamera_IsCxp(*args, **kwargs): ...
def InstantCamera_IsGigE(*args, **kwargs): ...
def InstantCamera_IsGrabbing(*args, **kwargs): ...
def InstantCamera_IsOpen(*args, **kwargs): ...
def InstantCamera_IsPylonDeviceAttached(*args, **kwargs): ...
def InstantCamera_IsUsb(*args, **kwargs): ...
def InstantCamera_Open(*args, **kwargs): ...
def InstantCamera_RegisterCameraEventHandler(*args, **kwargs): ...
def InstantCamera_RegisterConfiguration(*args, **kwargs): ...
def InstantCamera_RegisterImageEventHandler(*args, **kwargs): ...
def InstantCamera_RetrieveResult(*args, **kwargs): ...
def InstantCamera_SetBufferFactory(*args, **kwargs): ...
def InstantCamera_SetCameraContext(*args, **kwargs): ...
def InstantCamera_StartGrabbing(*args, **kwargs): ...
def InstantCamera_StartGrabbingMax(*args, **kwargs): ...
def InstantCamera_StopGrabbing(*args, **kwargs): ...
def InstantCamera_WaitForFrameTriggerReady(*args, **kwargs): ...
def InstantCamera_swiginit(*args, **kwargs): ...
def InstantCamera_swigregister(*args, **kwargs): ...
def InterfaceInfo_GetInterfaceID(*args, **kwargs): ...
def InterfaceInfo_IsInterfaceIDAvailable(*args, **kwargs): ...
def InterfaceInfo_SetInterfaceID(*args, **kwargs): ...
def InterfaceInfo___lt__(*args, **kwargs): ...
def InterfaceInfo_swiginit(*args, **kwargs): ...
def InterfaceInfo_swigregister(*args, **kwargs): ...
def Interface_Close(*args, **kwargs): ...
def Interface_GetInterfaceInfo(*args, **kwargs): ...
def Interface_GetNodeMap(*args, **kwargs): ...
def Interface_IsOpen(*args, **kwargs): ...
def Interface_Open(*args, **kwargs): ...
def Interface_swigregister(*args, **kwargs): ...
def IsBGR(*args, **kwargs): ...
def IsBGRA(*args, **kwargs): ...
def IsBGRPacked(*args, **kwargs): ...
def IsBayer(*args, **kwargs): ...
def IsBayerPacked(*args, **kwargs): ...
def IsBiColor(*args, **kwargs): ...
def IsBiColorPacked(*args, **kwargs): ...
def IsColorImage(*args, **kwargs): ...
def IsFloatingPoint(*args, **kwargs): ...
def IsMono(*args, **kwargs): ...
def IsMonoImage(*args, **kwargs): ...
def IsMonoPacked(*args, **kwargs): ...
def IsPacked(*args, **kwargs): ...
def IsPackedInLsbFormat(*args, **kwargs): ...
def IsPlanar(*args, **kwargs): ...
def IsRGB(*args, **kwargs): ...
def IsRGBA(*args, **kwargs): ...
def IsRGBPacked(*args, **kwargs): ...
def IsYUV(*args, **kwargs): ...
def IsYUVSemiplanar(*args, **kwargs): ...
def PlaneCount(*args, **kwargs): ...
def PylonDataComponent_GetComponentType(*args, **kwargs): ...
def PylonDataComponent_GetData(*args, **kwargs): ...
def PylonDataComponent_GetDataSize(*args, **kwargs): ...
def PylonDataComponent_GetHeight(*args, **kwargs): ...
def PylonDataComponent_GetMemoryView(*args, **kwargs): ...
def PylonDataComponent_GetOffsetX(*args, **kwargs): ...
def PylonDataComponent_GetOffsetY(*args, **kwargs): ...
def PylonDataComponent_GetPaddingX(*args, **kwargs): ...
def PylonDataComponent_GetPixelType(*args, **kwargs): ...
def PylonDataComponent_GetStride(*args, **kwargs): ...
def PylonDataComponent_GetTimeStamp(*args, **kwargs): ...
def PylonDataComponent_GetWidth(*args, **kwargs): ...
def PylonDataComponent_IsValid(*args, **kwargs): ...
def PylonDataComponent_Release(*args, **kwargs): ...
def PylonDataComponent__Unpack10or12BitPacked(*args, **kwargs): ...
def PylonDataComponent_swiginit(*args, **kwargs): ...
def PylonDataComponent_swigregister(*args, **kwargs): ...
def PylonDataContainer_GetDataComponent(*args, **kwargs): ...
def PylonDataContainer_GetDataComponentCount(*args, **kwargs): ...
def PylonDataContainer_Load(*args, **kwargs): ...
def PylonDataContainer_Release(*args, **kwargs): ...
def PylonDataContainer_Save(*args, **kwargs): ...
def PylonDataContainer_swiginit(*args, **kwargs): ...
def PylonDataContainer_swigregister(*args, **kwargs): ...
def PylonImageBase_CanSaveWithoutConversion(*args, **kwargs): ...
def PylonImageBase_GetPixelData(*args, **kwargs): ...
def PylonImageBase_Load(*args, **kwargs): ...
def PylonImageBase_Save(*args, **kwargs): ...
def PylonImageBase_swigregister(*args, **kwargs): ...
def PylonImageWindow_Attach(*args, **kwargs): ...
def PylonImageWindow_Close(*args, **kwargs): ...
def PylonImageWindow_Create(*args, **kwargs): ...
def PylonImageWindow_Detach(*args, **kwargs): ...
def PylonImageWindow_GetWindowHandle(*args, **kwargs): ...
def PylonImageWindow_GetWindowIndex(*args, **kwargs): ...
def PylonImageWindow_Hide(*args, **kwargs): ...
def PylonImageWindow_IsValid(*args, **kwargs): ...
def PylonImageWindow_SetImage(*args, **kwargs): ...
def PylonImageWindow_Show(*args, **kwargs): ...
def PylonImageWindow_swiginit(*args, **kwargs): ...
def PylonImageWindow_swigregister(*args, **kwargs): ...
def PylonImage_AttachBytesObject(*args, **kwargs): ...
def PylonImage_AttachGrabResultBuffer(*args, **kwargs): ...
def PylonImage_AttachGrabResultBufferWithUserHints(*args, **kwargs): ...
def PylonImage_AttachMemoryView(*args, **kwargs): ...
def PylonImage_ChangePixelType(*args, **kwargs): ...
def PylonImage_CopyImage(*args, **kwargs): ...
def PylonImage_Create(*args, **kwargs): ...
def PylonImage_GetAllocatedBufferSize(*args, **kwargs): ...
def PylonImage_GetAoi(*args, **kwargs): ...
def PylonImage_GetBuffer(*args, **kwargs): ...
def PylonImage_GetHeight(*args, **kwargs): ...
def PylonImage_GetImageSize(*args, **kwargs): ...
def PylonImage_GetMemoryView(*args, **kwargs): ...
def PylonImage_GetOrientation(*args, **kwargs): ...
def PylonImage_GetPaddingX(*args, **kwargs): ...
def PylonImage_GetPixelType(*args, **kwargs): ...
def PylonImage_GetPlane(*args, **kwargs): ...
def PylonImage_GetStride(*args, **kwargs): ...
def PylonImage_GetWidth(*args, **kwargs): ...
def PylonImage_IsAdditionalPaddingSupported(*args, **kwargs): ...
def PylonImage_IsGrabResultBufferAttached(*args, **kwargs): ...
def PylonImage_IsSupportedPixelType(*args, **kwargs): ...
def PylonImage_IsUnique(*args, **kwargs): ...
def PylonImage_IsUserBufferAttached(*args, **kwargs): ...
def PylonImage_IsValid(*args, **kwargs): ...
def PylonImage_Release(*args, **kwargs): ...
def PylonImage_Reset(*args, **kwargs): ...
def PylonImage_swiginit(*args, **kwargs): ...
def PylonImage_swigregister(*args, **kwargs): ...
def SamplesPerPixel(*args, **kwargs): ...
def SoftwareTriggerConfiguration_ApplyConfiguration(*args, **kwargs): ...
def SoftwareTriggerConfiguration_OnOpened(*args, **kwargs): ...
def SoftwareTriggerConfiguration_swiginit(*args, **kwargs): ...
def SoftwareTriggerConfiguration_swigregister(*args, **kwargs): ...
def SwigPyIterator___add__(*args, **kwargs): ...
def SwigPyIterator___eq__(*args, **kwargs): ...
def SwigPyIterator___iadd__(*args, **kwargs): ...
def SwigPyIterator___isub__(*args, **kwargs): ...
def SwigPyIterator___ne__(*args, **kwargs): ...
def SwigPyIterator___next__(*args, **kwargs): ...
def SwigPyIterator___sub__(*args, **kwargs): ...
def SwigPyIterator_advance(*args, **kwargs): ...
def SwigPyIterator_copy(*args, **kwargs): ...
def SwigPyIterator_decr(*args, **kwargs): ...
def SwigPyIterator_distance(*args, **kwargs): ...
def SwigPyIterator_equal(*args, **kwargs): ...
def SwigPyIterator_incr(*args, **kwargs): ...
def SwigPyIterator_next(*args, **kwargs): ...
def SwigPyIterator_previous(*args, **kwargs): ...
def SwigPyIterator_swigregister(*args, **kwargs): ...
def SwigPyIterator_value(*args, **kwargs): ...
def TlFactory_CreateDevice(*args, **kwargs): ...
def TlFactory_CreateFirstDevice(*args, **kwargs): ...
def TlFactory_CreateTl(*args, **kwargs): ...
def TlFactory_DestroyDevice(*args, **kwargs): ...
def TlFactory_EnumerateDevices(*args, **kwargs): ...
def TlFactory_EnumerateTls(*args, **kwargs): ...
def TlFactory_GetInstance(*args, **kwargs): ...
def TlFactory_IsDeviceAccessible(*args, **kwargs): ...
def TlFactory_ReleaseTl(*args, **kwargs): ...
def TlFactory_swigregister(*args, **kwargs): ...
def TlInfo_GetFileName(*args, **kwargs): ...
def TlInfo_GetInfoID(*args, **kwargs): ...
def TlInfo_GetModelName(*args, **kwargs): ...
def TlInfo_GetVersion(*args, **kwargs): ...
def TlInfo_IsFileNameAvailable(*args, **kwargs): ...
def TlInfo_IsInfoIDAvailable(*args, **kwargs): ...
def TlInfo_IsModelNameAvailable(*args, **kwargs): ...
def TlInfo_IsVersionAvailable(*args, **kwargs): ...
def TlInfo_SetFileName(*args, **kwargs): ...
def TlInfo_SetInfoID(*args, **kwargs): ...
def TlInfo_SetModelName(*args, **kwargs): ...
def TlInfo_SetVersion(*args, **kwargs): ...
def TlInfo_swiginit(*args, **kwargs): ...
def TlInfo_swigregister(*args, **kwargs): ...
def TransportLayer_CreateDeviceInfo(*args, **kwargs): ...
def TransportLayer_CreateInterface(*args, **kwargs): ...
def TransportLayer_DestroyInterface(*args, **kwargs): ...
def TransportLayer_EnumerateInterfaces(*args, **kwargs): ...
def TransportLayer_GetNodeMap(*args, **kwargs): ...
def TransportLayer_GetTlInfo(*args, **kwargs): ...
def TransportLayer_swigregister(*args, **kwargs): ...
def VersionInfo___eq__(*args, **kwargs): ...
def VersionInfo___ge__(*args, **kwargs): ...
def VersionInfo___gt__(*args, **kwargs): ...
def VersionInfo___le__(*args, **kwargs): ...
def VersionInfo___lt__(*args, **kwargs): ...
def VersionInfo___ne__(*args, **kwargs): ...
def VersionInfo_getBuild(*args, **kwargs): ...
def VersionInfo_getMajor(*args, **kwargs): ...
def VersionInfo_getMinor(*args, **kwargs): ...
def VersionInfo_getSubminor(*args, **kwargs): ...
def VersionInfo_swiginit(*args, **kwargs): ...
def VersionInfo_swigregister(*args, **kwargs): ...
def WaitObject_IsValid(*args, **kwargs): ...
def WaitObject_Sleep(*args, **kwargs): ...
def WaitObject_Wait(*args, **kwargs): ...
def WaitObject_WaitEx(*args, **kwargs): ...
def WaitObject_swiginit(*args, **kwargs): ...
def WaitObject_swigregister(*args, **kwargs): ...
def WaitObjects_Add(*args, **kwargs): ...
def WaitObjects_RemoveAll(*args, **kwargs): ...
def WaitObjects_WaitForAll(*args, **kwargs): ...
def WaitObjects_WaitForAllEx(*args, **kwargs): ...
def WaitObjects_WaitForAny(*args, **kwargs): ...
def WaitObjects_WaitForAnyEx(*args, **kwargs): ...
def WaitObjects_swiginit(*args, **kwargs): ...
def WaitObjects_swigregister(*args, **kwargs): ...
def delete_AcquireContinuousConfiguration(*args, **kwargs): ...
def delete_AcquireSingleFrameConfiguration(*args, **kwargs): ...
def delete_ActionTriggerConfiguration(*args, **kwargs): ...
def delete_CameraEventHandler(*args, **kwargs): ...
def delete_CompressionInfo(*args, **kwargs): ...
def delete_ConfigurationEventHandler(*args, **kwargs): ...
def delete_DeviceInfo(*args, **kwargs): ...
def delete_GrabResult(*args, **kwargs): ...
def delete_GrabResultData(*args, **kwargs): ...
def delete_IDeviceFactory(*args, **kwargs): ...
def delete_IReusableImage(*args, **kwargs): ...
def delete_Image(*args, **kwargs): ...
def delete_ImageDecompressor(*args, **kwargs): ...
def delete_ImageEventHandler(*args, **kwargs): ...
def delete_ImageFormatConverter(*args, **kwargs): ...
def delete_ImagePersistenceOptions(*args, **kwargs): ...
def delete_InstantCamera(*args, **kwargs): ...
def delete_InstantCameraArray(*args, **kwargs): ...
def delete_InterfaceInfo(*args, **kwargs): ...
def delete_PylonDataComponent(*args, **kwargs): ...
def delete_PylonDataContainer(*args, **kwargs): ...
def delete_PylonImage(*args, **kwargs): ...
def delete_PylonImageWindow(*args, **kwargs): ...
def delete_SoftwareTriggerConfiguration(*args, **kwargs): ...
def delete_SwigPyIterator(*args, **kwargs): ...
def delete_TlInfo(*args, **kwargs): ...
def delete_VersionInfo(*args, **kwargs): ...
def delete_WaitObject(*args, **kwargs): ...
def delete_WaitObjects(*args, **kwargs): ...
def disown_CameraEventHandler(*args, **kwargs): ...
def disown_ConfigurationEventHandler(*args, **kwargs): ...
def disown_ImageEventHandler(*args, **kwargs): ...
def new_AcquireContinuousConfiguration(*args, **kwargs): ...
def new_AcquireSingleFrameConfiguration(*args, **kwargs): ...
def new_ActionTriggerConfiguration(*args, **kwargs): ...
def new_CameraEventHandler(*args, **kwargs): ...
def new_CompressionInfo(*args, **kwargs): ...
def new_ConfigurationEventHandler(*args, **kwargs): ...
def new_DeviceInfo(*args, **kwargs): ...
def new_GrabResult(*args, **kwargs): ...
def new_ImageDecompressor(*args, **kwargs): ...
def new_ImageEventHandler(*args, **kwargs): ...
def new_ImageFormatConverter(*args, **kwargs): ...
def new_ImagePersistenceOptions(*args, **kwargs): ...
def new_InstantCamera(*args, **kwargs): ...
def new_InstantCameraArray(*args, **kwargs): ...
def new_InterfaceInfo(*args, **kwargs): ...
def new_PylonDataComponent(*args, **kwargs): ...
def new_PylonDataContainer(*args, **kwargs): ...
def new_PylonImage(*args, **kwargs): ...
def new_PylonImageWindow(*args, **kwargs): ...
def new_SoftwareTriggerConfiguration(*args, **kwargs): ...
def new_TlInfo(*args, **kwargs): ...
def new_VersionInfo(*args, **kwargs): ...
def new_WaitObject(*args, **kwargs): ...
def new_WaitObjects(*args, **kwargs): ...
