from typing import Any

import _typeshed

Automatic: int
Beginner: int
BigEndian: int
Boolean: int
CHUNK_BASE_ADDRESS_REGISTER_LEN: int
CHUNK_LENGTH_REGISTER_LEN: int
CL: int
Custom: int
Decreasing: int
Expert: int
GEV: int
Guru: int
HexNumber: int
IIDC: int
IPV4Address: int
Increasing: int
Invisible: int
Linear: int
LittleEndian: int
Logarithmic: int
MACAddress: int
NA: int
NI: int
No: int
NoCache: int
PureNumber: int
RO: int
RW: int
Signed: int
Standard: int
USB: int
Unsigned: int
Varying: int
WO: int
WriteAround: int
WriteThrough: int
Yes: int
cbPostInsideLock: int
cbPostOutsideLock: int
ctDependingNodes: int
ctInvalidatingChildren: int
ctParentNodes: int
ctReadingChildren: int
ctTerminalNodes: int
ctValueChangingChildren: int
ctWritingChildren: int
cvar: _typeshed.Incomplete
fixedIncrement: int
fnAutomatic: int
fnFixed: int
fnScientific: int
idFrom: int
idNone: int
idTo: int
intfIBase: int
intfIBoolean: int
intfICategory: int
intfICommand: int
intfIEnumEntry: int
intfIEnumeration: int
intfIFloat: int
intfIInteger: int
intfIPort: int
intfIRegister: int
intfIString: int
intfIValue: int
ios_base_copyfmt_event: int
ios_base_erase_event: int
ios_base_imbue_event: int
listIncrement: int
noIncrement: int
xvAll: int
xvCycles: int
xvDefault: int
xvLoad: int
xvSFNC: int

def AttachStatistics_t_NumAttachedChunks_get(*args, **kwargs): ...
def AttachStatistics_t_NumAttachedChunks_set(*args, **kwargs): ...
def AttachStatistics_t_NumChunkPorts_get(*args, **kwargs): ...
def AttachStatistics_t_NumChunkPorts_set(*args, **kwargs): ...
def AttachStatistics_t_NumChunks_get(*args, **kwargs): ...
def AttachStatistics_t_NumChunks_set(*args, **kwargs): ...
def AttachStatistics_t_swiginit(*args, **kwargs): ...
def AttachStatistics_t_swigregister(*args, **kwargs): ...
def CNodeMapRef_GetDeviceInfo(*args, **kwargs): ...
def CNodeMapRef_GetNode(*args, **kwargs): ...
def CNodeMapRef__ClearXMLCache(*args, **kwargs): ...
def CNodeMapRef__Connect(*args, **kwargs): ...
def CNodeMapRef__Destroy(*args, **kwargs): ...
def CNodeMapRef__GetDeviceName(*args, **kwargs): ...
def CNodeMapRef__GetNode(*args, **kwargs): ...
def CNodeMapRef__GetNodes(*args, **kwargs): ...
def CNodeMapRef__InvalidateNodes(*args, **kwargs): ...
def CNodeMapRef__LoadXMLFromFile(*args, **kwargs): ...
def CNodeMapRef__LoadXMLFromString(*args, **kwargs): ...
def CNodeMapRef__Poll(*args, **kwargs): ...
def CNodeMapRef__Ptr_get(*args, **kwargs): ...
def CNodeMapRef__Ptr_set(*args, **kwargs): ...
def CNodeMapRef_swiginit(*args, **kwargs): ...
def CNodeMapRef_swigregister(*args, **kwargs): ...
def CPortImpl_GetAccessMode(*args, **kwargs): ...
def CPortImpl_InvalidateNode(*args, **kwargs): ...
def CPortImpl_Read(*args, **kwargs): ...
def CPortImpl_Write(*args, **kwargs): ...
def CPortImpl_swiginit(*args, **kwargs): ...
def CPortImpl_swigregister(*args, **kwargs): ...
def CSelectorSet_GetSelectorList(*args, **kwargs): ...
def CSelectorSet_IsEmpty(*args, **kwargs): ...
def CSelectorSet_Restore(*args, **kwargs): ...
def CSelectorSet_SetFirst(*args, **kwargs): ...
def CSelectorSet_SetNext(*args, **kwargs): ...
def CSelectorSet_ToString(*args, **kwargs): ...
def CSelectorSet_swiginit(*args, **kwargs): ...
def CSelectorSet_swigregister(*args, **kwargs): ...
def ChunkAdapterGEV_AttachBuffer(*args, **kwargs): ...
def ChunkAdapterGEV_CheckBufferLayout(*args, **kwargs): ...
def ChunkAdapterGEV_swiginit(*args, **kwargs): ...
def ChunkAdapterGEV_swigregister(*args, **kwargs): ...
def ChunkAdapterGeneric_AttachBuffer(*args, **kwargs): ...
def ChunkAdapterGeneric_CheckBufferLayout(*args, **kwargs): ...
def ChunkAdapterGeneric_swiginit(*args, **kwargs): ...
def ChunkAdapterGeneric_swigregister(*args, **kwargs): ...
def ChunkAdapterU3V_AttachBuffer(*args, **kwargs): ...
def ChunkAdapterU3V_CheckBufferLayout(*args, **kwargs): ...
def ChunkAdapterU3V_swiginit(*args, **kwargs): ...
def ChunkAdapterU3V_swigregister(*args, **kwargs): ...
def ChunkAdapter_AttachBuffer(*args, **kwargs): ...
def ChunkAdapter_AttachNodeMap(*args, **kwargs): ...
def ChunkAdapter_CheckBufferLayout(*args, **kwargs): ...
def ChunkAdapter_ClearCaches(*args, **kwargs): ...
def ChunkAdapter_DetachBuffer(*args, **kwargs): ...
def ChunkAdapter_DetachNodeMap(*args, **kwargs): ...
def ChunkAdapter_UpdateBuffer(*args, **kwargs): ...
def ChunkAdapter_swigregister(*args, **kwargs): ...
def ChunkPort_AttachChunk(*args, **kwargs): ...
def ChunkPort_AttachPort(*args, **kwargs): ...
def ChunkPort_CheckChunkID(*args, **kwargs): ...
def ChunkPort_ClearCache(*args, **kwargs): ...
def ChunkPort_DetachChunk(*args, **kwargs): ...
def ChunkPort_DetachPort(*args, **kwargs): ...
def ChunkPort_GetAccessMode(*args, **kwargs): ...
def ChunkPort_GetChunkIDLength(*args, **kwargs): ...
def ChunkPort_GetPrincipalInterfaceType(*args, **kwargs): ...
def ChunkPort_GetSwapEndianess(*args, **kwargs): ...
def ChunkPort_InvalidateNode(*args, **kwargs): ...
def ChunkPort_Read(*args, **kwargs): ...
def ChunkPort_SetPortImpl(*args, **kwargs): ...
def ChunkPort_UpdateBuffer(*args, **kwargs): ...
def ChunkPort_Write(*args, **kwargs): ...
def ChunkPort_swiginit(*args, **kwargs): ...
def ChunkPort_swigregister(*args, **kwargs): ...
def Combine(*args, **kwargs): ...
def CombineCachingMode(*args, **kwargs): ...
def CombineVisibility(*args, **kwargs): ...
def Deregister(*args, **kwargs): ...
def EAccessModeClass_FromString(*args, **kwargs): ...
def EAccessModeClass_ToString(*args, **kwargs): ...
def EAccessModeClass_swiginit(*args, **kwargs): ...
def EAccessModeClass_swigregister(*args, **kwargs): ...
def ECachingModeClass_FromString(*args, **kwargs): ...
def ECachingModeClass_ToString(*args, **kwargs): ...
def ECachingModeClass_swiginit(*args, **kwargs): ...
def ECachingModeClass_swigregister(*args, **kwargs): ...
def EDisplayNotationClass_FromString(*args, **kwargs): ...
def EDisplayNotationClass_ToString(*args, **kwargs): ...
def EDisplayNotationClass_swiginit(*args, **kwargs): ...
def EDisplayNotationClass_swigregister(*args, **kwargs): ...
def EEndianessClass_FromString(*args, **kwargs): ...
def EEndianessClass_ToString(*args, **kwargs): ...
def EEndianessClass_swiginit(*args, **kwargs): ...
def EEndianessClass_swigregister(*args, **kwargs): ...
def EInputDirectionClass_FromString(*args, **kwargs): ...
def EInputDirectionClass_ToString(*args, **kwargs): ...
def EInputDirectionClass_swiginit(*args, **kwargs): ...
def EInputDirectionClass_swigregister(*args, **kwargs): ...
def ENameSpaceClass_FromString(*args, **kwargs): ...
def ENameSpaceClass_ToString(*args, **kwargs): ...
def ENameSpaceClass_swiginit(*args, **kwargs): ...
def ENameSpaceClass_swigregister(*args, **kwargs): ...
def ERepresentationClass_FromString(*args, **kwargs): ...
def ERepresentationClass_ToString(*args, **kwargs): ...
def ERepresentationClass_swiginit(*args, **kwargs): ...
def ERepresentationClass_swigregister(*args, **kwargs): ...
def ESignClass_FromString(*args, **kwargs): ...
def ESignClass_ToString(*args, **kwargs): ...
def ESignClass_swiginit(*args, **kwargs): ...
def ESignClass_swigregister(*args, **kwargs): ...
def ESlopeClass_FromString(*args, **kwargs): ...
def ESlopeClass_ToString(*args, **kwargs): ...
def ESlopeClass_swiginit(*args, **kwargs): ...
def ESlopeClass_swigregister(*args, **kwargs): ...
def EStandardNameSpaceClass_FromString(*args, **kwargs): ...
def EStandardNameSpaceClass_ToString(*args, **kwargs): ...
def EStandardNameSpaceClass_swiginit(*args, **kwargs): ...
def EStandardNameSpaceClass_swigregister(*args, **kwargs): ...
def EVisibilityClass_FromString(*args, **kwargs): ...
def EVisibilityClass_ToString(*args, **kwargs): ...
def EVisibilityClass_swiginit(*args, **kwargs): ...
def EVisibilityClass_swigregister(*args, **kwargs): ...
def EYesNoClass_FromString(*args, **kwargs): ...
def EYesNoClass_ToString(*args, **kwargs): ...
def EYesNoClass_swiginit(*args, **kwargs): ...
def EYesNoClass_swigregister(*args, **kwargs): ...
def EventAdapterGEV_DeliverMessage(*args, **kwargs): ...
def EventAdapterGEV_swiginit(*args, **kwargs): ...
def EventAdapterGEV_swigregister(*args, **kwargs): ...
def EventAdapterGeneric_DeliverMessage(*args, **kwargs): ...
def EventAdapterGeneric_swiginit(*args, **kwargs): ...
def EventAdapterGeneric_swigregister(*args, **kwargs): ...
def EventAdapterU3V_DeliverMessage(*args, **kwargs): ...
def EventAdapterU3V_swiginit(*args, **kwargs): ...
def EventAdapterU3V_swigregister(*args, **kwargs): ...
def EventAdapter_AttachNodeMap(*args, **kwargs): ...
def EventAdapter_DeliverMessage(*args, **kwargs): ...
def EventAdapter_DetachNodeMap(*args, **kwargs): ...
def EventAdapter_swigregister(*args, **kwargs): ...
def EventPort_AttachEvent(*args, **kwargs): ...
def EventPort_AttachNode(*args, **kwargs): ...
def EventPort_CheckEventID(*args, **kwargs): ...
def EventPort_DetachEvent(*args, **kwargs): ...
def EventPort_DetachNode(*args, **kwargs): ...
def EventPort_GetAccessMode(*args, **kwargs): ...
def EventPort_GetEventIDLength(*args, **kwargs): ...
def EventPort_GetPrincipalInterfaceType(*args, **kwargs): ...
def EventPort_GetSwapEndianess(*args, **kwargs): ...
def EventPort_InvalidateNode(*args, **kwargs): ...
def EventPort_Read(*args, **kwargs): ...
def EventPort_SetPortImpl(*args, **kwargs): ...
def EventPort_Write(*args, **kwargs): ...
def EventPort_swiginit(*args, **kwargs): ...
def EventPort_swigregister(*args, **kwargs): ...
def FileProtocolAdapter_attach(*args, **kwargs): ...
def FileProtocolAdapter_closeFile(*args, **kwargs): ...
def FileProtocolAdapter_deleteFile(*args, **kwargs): ...
def FileProtocolAdapter_getBufSize(*args, **kwargs): ...
def FileProtocolAdapter_openFile(*args, **kwargs): ...
def FileProtocolAdapter_read(*args, **kwargs): ...
def FileProtocolAdapter_swiginit(*args, **kwargs): ...
def FileProtocolAdapter_swigregister(*args, **kwargs): ...
def FileProtocolAdapter_write(*args, **kwargs): ...
def GVCP_CHUNK_TRAILER_ChunkID_get(*args, **kwargs): ...
def GVCP_CHUNK_TRAILER_ChunkID_set(*args, **kwargs): ...
def GVCP_CHUNK_TRAILER_ChunkLength_get(*args, **kwargs): ...
def GVCP_CHUNK_TRAILER_ChunkLength_set(*args, **kwargs): ...
def GVCP_CHUNK_TRAILER_swiginit(*args, **kwargs): ...
def GVCP_CHUNK_TRAILER_swigregister(*args, **kwargs): ...
def IBase_GetAccessMode(*args, **kwargs): ...
def IBase_swigregister(*args, **kwargs): ...
def IBoolean_GetValue(*args, **kwargs): ...
def IBoolean_SetValue(*args, **kwargs): ...
def IBoolean___call__(*args, **kwargs): ...
def IBoolean_swigregister(*args, **kwargs): ...
def ICategory_GetFeatures(*args, **kwargs): ...
def ICategory_swigregister(*args, **kwargs): ...
def IChunkPort_CacheChunkData(*args, **kwargs): ...
def IChunkPort_GetChunkID(*args, **kwargs): ...
def IChunkPort_swigregister(*args, **kwargs): ...
def ICommand_Execute(*args, **kwargs): ...
def ICommand_IsDone(*args, **kwargs): ...
def ICommand___call__(*args, **kwargs): ...
def ICommand_swigregister(*args, **kwargs): ...
def IDeviceInfo_GetDeviceVersion(*args, **kwargs): ...
def IDeviceInfo_GetGenApiVersion(*args, **kwargs): ...
def IDeviceInfo_GetModelName(*args, **kwargs): ...
def IDeviceInfo_GetProductGuid(*args, **kwargs): ...
def IDeviceInfo_GetSchemaVersion(*args, **kwargs): ...
def IDeviceInfo_GetStandardNameSpace(*args, **kwargs): ...
def IDeviceInfo_GetToolTip(*args, **kwargs): ...
def IDeviceInfo_GetVendorName(*args, **kwargs): ...
def IDeviceInfo_GetVersionGuid(*args, **kwargs): ...
def IDeviceInfo_swigregister(*args, **kwargs): ...
def IEnumEntry_GetNumericValue(*args, **kwargs): ...
def IEnumEntry_GetSymbolic(*args, **kwargs): ...
def IEnumEntry_GetValue(*args, **kwargs): ...
def IEnumEntry_IsSelfClearing(*args, **kwargs): ...
def IEnumEntry_swigregister(*args, **kwargs): ...
def IEnumReference_SetEnumReference(*args, **kwargs): ...
def IEnumReference_SetNumEnums(*args, **kwargs): ...
def IEnumReference_swigregister(*args, **kwargs): ...
def IEnumeration_GetCurrentEntry(*args, **kwargs): ...
def IEnumeration_GetEntries(*args, **kwargs): ...
def IEnumeration_GetEntry(*args, **kwargs): ...
def IEnumeration_GetEntryByName(*args, **kwargs): ...
def IEnumeration_GetIntValue(*args, **kwargs): ...
def IEnumeration_GetSymbolics(*args, **kwargs): ...
def IEnumeration_GetValue(*args, **kwargs): ...
def IEnumeration_SetIntValue(*args, **kwargs): ...
def IEnumeration_SetValue(*args, **kwargs): ...
def IEnumeration___call__(*args, **kwargs): ...
def IEnumeration_swigregister(*args, **kwargs): ...
def IFloat_GetDisplayNotation(*args, **kwargs): ...
def IFloat_GetDisplayPrecision(*args, **kwargs): ...
def IFloat_GetEnumAlias(*args, **kwargs): ...
def IFloat_GetInc(*args, **kwargs): ...
def IFloat_GetIncMode(*args, **kwargs): ...
def IFloat_GetIntAlias(*args, **kwargs): ...
def IFloat_GetListOfValidValues(*args, **kwargs): ...
def IFloat_GetMax(*args, **kwargs): ...
def IFloat_GetMin(*args, **kwargs): ...
def IFloat_GetRepresentation(*args, **kwargs): ...
def IFloat_GetUnit(*args, **kwargs): ...
def IFloat_GetValue(*args, **kwargs): ...
def IFloat_HasInc(*args, **kwargs): ...
def IFloat_ImposeMax(*args, **kwargs): ...
def IFloat_ImposeMin(*args, **kwargs): ...
def IFloat_SetValue(*args, **kwargs): ...
def IFloat___call__(*args, **kwargs): ...
def IFloat_swigregister(*args, **kwargs): ...
def IInteger_Get(*args, **kwargs): ...
def IInteger_GetAddress(*args, **kwargs): ...
def IInteger_GetFloatAlias(*args, **kwargs): ...
def IInteger_GetInc(*args, **kwargs): ...
def IInteger_GetIncMode(*args, **kwargs): ...
def IInteger_GetLength(*args, **kwargs): ...
def IInteger_GetListOfValidValues(*args, **kwargs): ...
def IInteger_GetMax(*args, **kwargs): ...
def IInteger_GetMin(*args, **kwargs): ...
def IInteger_GetRepresentation(*args, **kwargs): ...
def IInteger_GetUnit(*args, **kwargs): ...
def IInteger_GetValue(*args, **kwargs): ...
def IInteger_ImposeMax(*args, **kwargs): ...
def IInteger_ImposeMin(*args, **kwargs): ...
def IInteger_Set(*args, **kwargs): ...
def IInteger_SetValue(*args, **kwargs): ...
def IInteger___call__(*args, **kwargs): ...
def IInteger_swigregister(*args, **kwargs): ...
def INodeMap_Connect(*args, **kwargs): ...
def INodeMap_GetDeviceInfo(*args, **kwargs): ...
def INodeMap_GetDeviceName(*args, **kwargs): ...
def INodeMap_GetLock(*args, **kwargs): ...
def INodeMap_GetNode(*args, **kwargs): ...
def INodeMap_GetNodes(*args, **kwargs): ...
def INodeMap_GetNumNodes(*args, **kwargs): ...
def INodeMap_InvalidateNodes(*args, **kwargs): ...
def INodeMap_ParseSwissKnifes(*args, **kwargs): ...
def INodeMap_Poll(*args, **kwargs): ...
def INodeMap_swigregister(*args, **kwargs): ...
def INode_DeregisterCallback(*args, **kwargs): ...
def INode_GetAlias(*args, **kwargs): ...
def INode_GetCachingMode(*args, **kwargs): ...
def INode_GetCastAlias(*args, **kwargs): ...
def INode_GetChildren(*args, **kwargs): ...
def INode_GetDescription(*args, **kwargs): ...
def INode_GetDeviceName(*args, **kwargs): ...
def INode_GetDisplayName(*args, **kwargs): ...
def INode_GetDocuURL(*args, **kwargs): ...
def INode_GetEventID(*args, **kwargs): ...
def INode_GetName(*args, **kwargs): ...
def INode_GetNameSpace(*args, **kwargs): ...
def INode_GetNodeMap(*args, **kwargs): ...
def INode_GetParents(*args, **kwargs): ...
def INode_GetPollingTime(*args, **kwargs): ...
def INode_GetPrincipalInterfaceType(*args, **kwargs): ...
def INode_GetProperty(*args, **kwargs): ...
def INode_GetPropertyNames(*args, **kwargs): ...
def INode_GetSelectedFeatures(*args, **kwargs): ...
def INode_GetSelectingFeatures(*args, **kwargs): ...
def INode_GetToolTip(*args, **kwargs): ...
def INode_GetVisibility(*args, **kwargs): ...
def INode_ImposeAccessMode(*args, **kwargs): ...
def INode_ImposeVisibility(*args, **kwargs): ...
def INode_InvalidateNode(*args, **kwargs): ...
def INode_IsAccessModeCacheable(*args, **kwargs): ...
def INode_IsCachable(*args, **kwargs): ...
def INode_IsDeprecated(*args, **kwargs): ...
def INode_IsFeature(*args, **kwargs): ...
def INode_IsSelector(*args, **kwargs): ...
def INode_IsStreamable(*args, **kwargs): ...
def INode_RegisterCallback(*args, **kwargs): ...
def INode_swigregister(*args, **kwargs): ...
def IPortConstruct_GetSwapEndianess(*args, **kwargs): ...
def IPortConstruct_swigregister(*args, **kwargs): ...
def IPortRecorder_StartRecording(*args, **kwargs): ...
def IPortRecorder_StopRecording(*args, **kwargs): ...
def IPortRecorder_swigregister(*args, **kwargs): ...
def IPortReplay_Replay(*args, **kwargs): ...
def IPortReplay_swigregister(*args, **kwargs): ...
def IPortWriteList_GetCookie(*args, **kwargs): ...
def IPortWriteList_Replay(*args, **kwargs): ...
def IPortWriteList_SetCookie(*args, **kwargs): ...
def IPortWriteList_Write(*args, **kwargs): ...
def IPortWriteList_swigregister(*args, **kwargs): ...
def IPort_CacheChunkData(*args, **kwargs): ...
def IPort_GetChunkID(*args, **kwargs): ...
def IPort_GetNode(*args, **kwargs): ...
def IPort_GetSwapEndianess(*args, **kwargs): ...
def IPort_Read(*args, **kwargs): ...
def IPort_Write(*args, **kwargs): ...
def IPort_swigregister(*args, **kwargs): ...
def IReference_SetReference(*args, **kwargs): ...
def IReference_swigregister(*args, **kwargs): ...
def IRegister_Get(*args, **kwargs): ...
def IRegister_GetAddress(*args, **kwargs): ...
def IRegister_GetLength(*args, **kwargs): ...
def IRegister_Set(*args, **kwargs): ...
def IRegister_swigregister(*args, **kwargs): ...
def ISelectorDigit_GetSelectorList(*args, **kwargs): ...
def ISelectorDigit_Restore(*args, **kwargs): ...
def ISelectorDigit_SetFirst(*args, **kwargs): ...
def ISelectorDigit_SetNext(*args, **kwargs): ...
def ISelectorDigit_ToString(*args, **kwargs): ...
def ISelectorDigit_swigregister(*args, **kwargs): ...
def ISelector_swigregister(*args, **kwargs): ...
def IString_GetLength(*args, **kwargs): ...
def IString_GetMaxLength(*args, **kwargs): ...
def IString_GetValue(*args, **kwargs): ...
def IString_SetValue(*args, **kwargs): ...
def IString___call__(*args, **kwargs): ...
def IString_swigregister(*args, **kwargs): ...
def IValue_FromString(*args, **kwargs): ...
def IValue_GetNode(*args, **kwargs): ...
def IValue_IsValueCacheValid(*args, **kwargs): ...
def IValue_ToString(*args, **kwargs): ...
def IValue_swigregister(*args, **kwargs): ...
def IsAvailable(*args, **kwargs): ...
def IsCacheable(*args, **kwargs): ...
def IsImplemented(*args, **kwargs): ...
def IsReadable(*args, **kwargs): ...
def IsVisible(*args, **kwargs): ...
def IsWritable(*args, **kwargs): ...
def PyNodeCallback_GetNode(*args, **kwargs): ...
def PyNodeCallback_swiginit(*args, **kwargs): ...
def PyNodeCallback_swigregister(*args, **kwargs): ...
def SingleChunkDataStr_t_ChunkID_get(*args, **kwargs): ...
def SingleChunkDataStr_t_ChunkID_set(*args, **kwargs): ...
def SingleChunkDataStr_t_ChunkLength_get(*args, **kwargs): ...
def SingleChunkDataStr_t_ChunkLength_set(*args, **kwargs): ...
def SingleChunkDataStr_t_ChunkOffset_get(*args, **kwargs): ...
def SingleChunkDataStr_t_ChunkOffset_set(*args, **kwargs): ...
def SingleChunkDataStr_t_swiginit(*args, **kwargs): ...
def SingleChunkDataStr_t_swigregister(*args, **kwargs): ...
def SingleChunkData_t_ChunkID_get(*args, **kwargs): ...
def SingleChunkData_t_ChunkID_set(*args, **kwargs): ...
def SingleChunkData_t_ChunkLength_get(*args, **kwargs): ...
def SingleChunkData_t_ChunkLength_set(*args, **kwargs): ...
def SingleChunkData_t_ChunkOffset_get(*args, **kwargs): ...
def SingleChunkData_t_ChunkOffset_set(*args, **kwargs): ...
def SingleChunkData_t_swiginit(*args, **kwargs): ...
def SingleChunkData_t_swigregister(*args, **kwargs): ...
def SwigPyIterator___add__(*args, **kwargs): ...
def SwigPyIterator___eq__(*args, **kwargs): ...
def SwigPyIterator___iadd__(*args, **kwargs): ...
def SwigPyIterator___isub__(*args, **kwargs): ...
def SwigPyIterator___ne__(*args, **kwargs): ...
def SwigPyIterator___next__(*args, **kwargs): ...
def SwigPyIterator___sub__(*args, **kwargs): ...
def SwigPyIterator_advance(*args, **kwargs): ...
def SwigPyIterator_copy(*args, **kwargs): ...
def SwigPyIterator_decr(*args, **kwargs): ...
def SwigPyIterator_distance(*args, **kwargs): ...
def SwigPyIterator_equal(*args, **kwargs): ...
def SwigPyIterator_incr(*args, **kwargs): ...
def SwigPyIterator_next(*args, **kwargs): ...
def SwigPyIterator_previous(*args, **kwargs): ...
def SwigPyIterator_swigregister(*args, **kwargs): ...
def SwigPyIterator_value(*args, **kwargs): ...
def TranslateGenicamException(*args, **kwargs): ...
def U3V_CHUNK_TRAILER_ChunkID_get(*args, **kwargs): ...
def U3V_CHUNK_TRAILER_ChunkID_set(*args, **kwargs): ...
def U3V_CHUNK_TRAILER_ChunkLength_get(*args, **kwargs): ...
def U3V_CHUNK_TRAILER_ChunkLength_set(*args, **kwargs): ...
def U3V_CHUNK_TRAILER_swiginit(*args, **kwargs): ...
def U3V_CHUNK_TRAILER_swigregister(*args, **kwargs): ...
def Version_Major_get(*args, **kwargs): ...
def Version_Major_set(*args, **kwargs): ...
def Version_Minor_get(*args, **kwargs): ...
def Version_Minor_set(*args, **kwargs): ...
def Version_SubMinor_get(*args, **kwargs): ...
def Version_SubMinor_set(*args, **kwargs): ...
def Version_swiginit(*args, **kwargs): ...
def Version_swigregister(*args, **kwargs): ...
def delete_AttachStatistics_t(*args, **kwargs): ...
def delete_CNodeMapRef(*args, **kwargs): ...
def delete_CPortImpl(*args, **kwargs): ...
def delete_CSelectorSet(*args, **kwargs): ...
def delete_ChunkAdapter(*args, **kwargs): ...
def delete_ChunkAdapterGEV(*args, **kwargs): ...
def delete_ChunkAdapterGeneric(*args, **kwargs): ...
def delete_ChunkAdapterU3V(*args, **kwargs): ...
def delete_ChunkPort(*args, **kwargs): ...
def delete_EAccessModeClass(*args, **kwargs): ...
def delete_ECachingModeClass(*args, **kwargs): ...
def delete_EDisplayNotationClass(*args, **kwargs): ...
def delete_EEndianessClass(*args, **kwargs): ...
def delete_EInputDirectionClass(*args, **kwargs): ...
def delete_ENameSpaceClass(*args, **kwargs): ...
def delete_ERepresentationClass(*args, **kwargs): ...
def delete_ESignClass(*args, **kwargs): ...
def delete_ESlopeClass(*args, **kwargs): ...
def delete_EStandardNameSpaceClass(*args, **kwargs): ...
def delete_EVisibilityClass(*args, **kwargs): ...
def delete_EYesNoClass(*args, **kwargs): ...
def delete_EventAdapter(*args, **kwargs): ...
def delete_EventAdapterGEV(*args, **kwargs): ...
def delete_EventAdapterGeneric(*args, **kwargs): ...
def delete_EventAdapterU3V(*args, **kwargs): ...
def delete_EventPort(*args, **kwargs): ...
def delete_FileProtocolAdapter(*args, **kwargs): ...
def delete_GVCP_CHUNK_TRAILER(*args, **kwargs): ...
def delete_PyNodeCallback(*args, **kwargs): ...
def delete_SingleChunkDataStr_t(*args, **kwargs): ...
def delete_SingleChunkData_t(*args, **kwargs): ...
def delete_SwigPyIterator(*args, **kwargs): ...
def delete_U3V_CHUNK_TRAILER(*args, **kwargs): ...
def delete_Version(*args, **kwargs): ...
def delete_ios(*args, **kwargs): ...
def delete_ios_base(*args, **kwargs): ...
def delete_node_vector(*args, **kwargs): ...
def delete_string_vector(*args, **kwargs): ...
def delete_value_vector(*args, **kwargs): ...
def disown_CPortImpl(*args, **kwargs): ...
def ios_bad(*args, **kwargs): ...
def ios_base_flags(*args, **kwargs): ...
def ios_base_getloc(*args, **kwargs): ...
def ios_base_imbue(*args, **kwargs): ...
def ios_base_iword(*args, **kwargs): ...
def ios_base_precision(*args, **kwargs): ...
def ios_base_pword(*args, **kwargs): ...
def ios_base_register_callback(*args, **kwargs): ...
def ios_base_setf(*args, **kwargs): ...
def ios_base_swigregister(*args, **kwargs): ...
def ios_base_sync_with_stdio(*args, **kwargs): ...
def ios_base_unsetf(*args, **kwargs): ...
def ios_base_width(*args, **kwargs): ...
def ios_base_xalloc(*args, **kwargs): ...
def ios_clear(*args, **kwargs): ...
def ios_copyfmt(*args, **kwargs): ...
def ios_eof(*args, **kwargs): ...
def ios_exceptions(*args, **kwargs): ...
def ios_fail(*args, **kwargs): ...
def ios_fill(*args, **kwargs): ...
def ios_good(*args, **kwargs): ...
def ios_imbue(*args, **kwargs): ...
def ios_narrow(*args, **kwargs): ...
def ios_rdbuf(*args, **kwargs): ...
def ios_rdstate(*args, **kwargs): ...
def ios_setstate(*args, **kwargs): ...
def ios_swiginit(*args, **kwargs): ...
def ios_swigregister(*args, **kwargs): ...
def ios_tie(*args, **kwargs): ...
def ios_widen(*args, **kwargs): ...
def new_AttachStatistics_t(*args, **kwargs): ...
def new_CNodeMapRef(*args, **kwargs): ...
def new_CPortImpl(*args, **kwargs): ...
def new_CSelectorSet(*args, **kwargs): ...
def new_ChunkAdapterGEV(*args, **kwargs): ...
def new_ChunkAdapterGeneric(*args, **kwargs): ...
def new_ChunkAdapterU3V(*args, **kwargs): ...
def new_ChunkPort(*args, **kwargs): ...
def new_EAccessModeClass(*args, **kwargs): ...
def new_ECachingModeClass(*args, **kwargs): ...
def new_EDisplayNotationClass(*args, **kwargs): ...
def new_EEndianessClass(*args, **kwargs): ...
def new_EInputDirectionClass(*args, **kwargs): ...
def new_ENameSpaceClass(*args, **kwargs): ...
def new_ERepresentationClass(*args, **kwargs): ...
def new_ESignClass(*args, **kwargs): ...
def new_ESlopeClass(*args, **kwargs): ...
def new_EStandardNameSpaceClass(*args, **kwargs): ...
def new_EVisibilityClass(*args, **kwargs): ...
def new_EYesNoClass(*args, **kwargs): ...
def new_EventAdapterGEV(*args, **kwargs): ...
def new_EventAdapterGeneric(*args, **kwargs): ...
def new_EventAdapterU3V(*args, **kwargs): ...
def new_EventPort(*args, **kwargs): ...
def new_FileProtocolAdapter(*args, **kwargs): ...
def new_GVCP_CHUNK_TRAILER(*args, **kwargs): ...
def new_PyNodeCallback(*args, **kwargs): ...
def new_SingleChunkDataStr_t(*args, **kwargs): ...
def new_SingleChunkData_t(*args, **kwargs): ...
def new_U3V_CHUNK_TRAILER(*args, **kwargs): ...
def new_Version(*args, **kwargs): ...
def new_ios(*args, **kwargs): ...
def new_node_vector(*args, **kwargs): ...
def new_string_vector(*args, **kwargs): ...
def new_value_vector(*args, **kwargs): ...
def node_vector___bool__(*args, **kwargs): ...
def node_vector___delitem__(*args, **kwargs): ...
def node_vector___delslice__(*args, **kwargs): ...
def node_vector___getitem__(*args, **kwargs): ...
def node_vector___getslice__(*args, **kwargs): ...
def node_vector___len__(*args, **kwargs): ...
def node_vector___nonzero__(*args, **kwargs): ...
def node_vector___setitem__(*args, **kwargs): ...
def node_vector___setslice__(*args, **kwargs): ...
def node_vector_append(*args, **kwargs): ...
def node_vector_assign(*args, **kwargs): ...
def node_vector_back(*args, **kwargs): ...
def node_vector_begin(*args, **kwargs): ...
def node_vector_capacity(*args, **kwargs): ...
def node_vector_clear(*args, **kwargs): ...
def node_vector_empty(*args, **kwargs): ...
def node_vector_end(*args, **kwargs): ...
def node_vector_erase(*args, **kwargs): ...
def node_vector_front(*args, **kwargs): ...
def node_vector_get_allocator(*args, **kwargs): ...
def node_vector_insert(*args, **kwargs): ...
def node_vector_iterator(*args, **kwargs): ...
def node_vector_pop(*args, **kwargs): ...
def node_vector_pop_back(*args, **kwargs): ...
def node_vector_push_back(*args, **kwargs): ...
def node_vector_rbegin(*args, **kwargs): ...
def node_vector_rend(*args, **kwargs): ...
def node_vector_reserve(*args, **kwargs): ...
def node_vector_resize(*args, **kwargs): ...
def node_vector_size(*args, **kwargs): ...
def node_vector_swap(*args, **kwargs): ...
def node_vector_swiginit(*args, **kwargs): ...
def node_vector_swigregister(*args, **kwargs): ...
def string_vector___bool__(*args, **kwargs): ...
def string_vector___delitem__(*args, **kwargs): ...
def string_vector___delslice__(*args, **kwargs): ...
def string_vector___getitem__(*args, **kwargs): ...
def string_vector___getslice__(*args, **kwargs): ...
def string_vector___len__(*args, **kwargs): ...
def string_vector___nonzero__(*args, **kwargs): ...
def string_vector___setitem__(*args, **kwargs): ...
def string_vector___setslice__(*args, **kwargs): ...
def string_vector_append(*args, **kwargs): ...
def string_vector_assign(*args, **kwargs): ...
def string_vector_back(*args, **kwargs): ...
def string_vector_begin(*args, **kwargs): ...
def string_vector_capacity(*args, **kwargs): ...
def string_vector_clear(*args, **kwargs): ...
def string_vector_empty(*args, **kwargs): ...
def string_vector_end(*args, **kwargs): ...
def string_vector_erase(*args, **kwargs): ...
def string_vector_front(*args, **kwargs): ...
def string_vector_get_allocator(*args, **kwargs): ...
def string_vector_insert(*args, **kwargs): ...
def string_vector_iterator(*args, **kwargs): ...
def string_vector_pop(*args, **kwargs): ...
def string_vector_pop_back(*args, **kwargs): ...
def string_vector_push_back(*args, **kwargs): ...
def string_vector_rbegin(*args, **kwargs): ...
def string_vector_rend(*args, **kwargs): ...
def string_vector_reserve(*args, **kwargs): ...
def string_vector_resize(*args, **kwargs): ...
def string_vector_size(*args, **kwargs): ...
def string_vector_swap(*args, **kwargs): ...
def string_vector_swiginit(*args, **kwargs): ...
def string_vector_swigregister(*args, **kwargs): ...
def value_vector___bool__(*args, **kwargs): ...
def value_vector___delitem__(*args, **kwargs): ...
def value_vector___delslice__(*args, **kwargs): ...
def value_vector___getitem__(*args, **kwargs): ...
def value_vector___getslice__(*args, **kwargs): ...
def value_vector___len__(*args, **kwargs): ...
def value_vector___nonzero__(*args, **kwargs): ...
def value_vector___setitem__(*args, **kwargs): ...
def value_vector___setslice__(*args, **kwargs): ...
def value_vector_append(*args, **kwargs): ...
def value_vector_assign(*args, **kwargs): ...
def value_vector_back(*args, **kwargs): ...
def value_vector_begin(*args, **kwargs): ...
def value_vector_capacity(*args, **kwargs): ...
def value_vector_clear(*args, **kwargs): ...
def value_vector_empty(*args, **kwargs): ...
def value_vector_end(*args, **kwargs): ...
def value_vector_erase(*args, **kwargs): ...
def value_vector_front(*args, **kwargs): ...
def value_vector_get_allocator(*args, **kwargs): ...
def value_vector_insert(*args, **kwargs): ...
def value_vector_iterator(*args, **kwargs): ...
def value_vector_pop(*args, **kwargs): ...
def value_vector_pop_back(*args, **kwargs): ...
def value_vector_push_back(*args, **kwargs): ...
def value_vector_rbegin(*args, **kwargs): ...
def value_vector_rend(*args, **kwargs): ...
def value_vector_reserve(*args, **kwargs): ...
def value_vector_resize(*args, **kwargs): ...
def value_vector_size(*args, **kwargs): ...
def value_vector_swap(*args, **kwargs): ...
def value_vector_swiginit(*args, **kwargs): ...
def value_vector_swigregister(*args, **kwargs): ...

class INode:
    def GetName(self) -> str: ...
    def GetDescription(self) -> str: ...
    def IsReadable(self) -> bool: ...
    def IsWritable(self) -> bool: ...

class IBoolean(INode):
    def GetValue(self) -> bool: ...
    def SetValue(self, value: bool) -> None: ...

class IInteger(INode):
    def GetValue(self) -> int: ...
    def SetValue(self, value: int, verify: bool = True) -> None: ...
    def GetMin(self) -> int: ...
    def GetMax(self) -> int: ...

class IFloat(INode):
    def GetValue(self) -> float: ...
    def SetValue(self, value: float, verify: bool = True) -> None: ...
    def GetMin(self) -> bool: ...
    def GetMax(self) -> bool: ...

class IEnumeration(INode):
    def GetValue(self) -> str: ...
    def SetValue(self, value: str | int) -> None: ...
    def GetSymbolics(self) -> list[str]: ...
