from types import TracebackType
from typing import Any, Self

import numpy as np
from pypylon.genicam import IBoolean, IEnumeration, IFloat, IInteger

GenericException = Exception
BadAllocException = Exception
InvalidArgumentException = Exception
OutOfRangeException = Exception
PropertyException = Exception
RuntimeException = Exception
LogicalErrorException = Exception
AccessException = Exception
TimeoutException = Exception
DynamicCastException = Exception

GrabStrategy_OneByOne: int  # 出力キューに順次保持される
GrabStrategy_LatestImageOnly: int  # 最新の画像だけ出力キューに保持
GrabStrategy_LatestImages: int  # 最後から指定した数の画像が出力キューに保持
GrabStrategy_UpcomingImage: int  # RetrieveResultメソッドが呼ばれてから出力キューに保持

TimeoutHandling_Return: int
TimeoutHandling_ThrowException: int

PixelType_Mono12: int
PixelType_Mono16: int
OutputBitAlignment_LsbAligned: Any
OutputBitAlignment_MsbAligned: Any

class NodeMap:
    def GetNode(self, name: str) -> Any: ...
    # camera.ExposureTime.SetValue() のようなドットアクセスを Any で許容する
    def __getattr__(self, name: str) -> Any: ...

class DeviceInfo:
    def GetDeviceClass(self) -> str: ...
    def GetModelName(self) -> str: ...

class GrabResult:
    def GrabSucceeded(self) -> bool: ...
    def GetArray(self) -> np.ndarray: ...
    def Release(self) -> None: ...
    def GetErrorCode(self) -> int: ...
    def GetErrorDescription(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, typ: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None
    ) -> None: ...

class ImageFormatConverter:
    def Convert(self, result: GrabResult) -> PylonImage: ...

    OutputPixelFormat: int
    OutputBitAlignment: IEnumeration

class PylonImage:
    def GetArray(self) -> np.ndarray: ...
    def GetHeight(self) -> int: ...
    def GetWidth(self) -> int: ...

class InstantCamera:
    def __init__(self, device: DeviceInfo) -> None: ...
    def IsOpen(self) -> bool: ...
    def Open(self) -> None: ...
    def Close(self) -> None: ...
    def GrabOne(self, timeoutMs: int) -> GrabResult: ...
    def IsGrabbing(self) -> bool: ...
    def StartGrabbing(self, strategy: int = ...) -> None: ...
    def StopGrabbing(self) -> None: ...
    def RetrieveResult(self, timeout: int, strategy: int = ...) -> GrabResult: ...
    def GetNodeMap(self) -> NodeMap: ...
    def GetDeviceInfo(self) -> DeviceInfo: ...
    # camera.ExposureTime などへのアクセスを補完対象にする
    def __getattr__(self, name: str) -> Any: ...

    PixelFormat: IEnumeration

    ExposureAuto: IEnumeration
    ExposureTimeRaw: IInteger
    ExposureTimeAbs: IFloat
    GainAuto: IEnumeration
    GainRaw: IInteger
    Gamma: IFloat

    ReverseX: IBoolean
    ReverseY: IBoolean

class TlFactory:
    @staticmethod
    def GetInstance() -> TlFactory: ...
    def CreateFirstDevice(self) -> DeviceInfo: ...
    def EnumerateDevices(self) -> tuple[DeviceInfo]: ...
