from __future__ import annotations

from rheed_capture.domain.angle_scan.model import MIN_ANGLE_INTERVAL_DEG, AngleScanDirection

DEFAULT_EXPOSURE_MS_VALUES: tuple[float, ...] = (10.0, 50.0, 100.0)
DEFAULT_GAIN_VALUES: tuple[int, ...] = (0, 5, 10)

DEFAULT_PREVIEW_EXPOSURE_MS = 50.0
DEFAULT_PREVIEW_GAIN = 0
DEFAULT_PREVIEW_CLAHE_ENABLED = False
DEFAULT_PREVIEW_GRID_ENABLED = False
DEFAULT_PREVIEW_GRID_ROWS = 4
DEFAULT_PREVIEW_GRID_COLS = 4

DEFAULT_ANGLE_SCAN_RANGE_DEG = 5.0
DEFAULT_ANGLE_SCAN_INTERVAL_DEG = MIN_ANGLE_INTERVAL_DEG
DEFAULT_ANGLE_SCAN_DIRECTION: AngleScanDirection = "both"
DEFAULT_ANGLE_SCAN_WAIT_AFTER_MOVE_MS = 1000
DEFAULT_ANGLE_SCAN_RETURN_TO_START = False

DEFAULT_MOTOR_DRIVER = "azd_cd"
